import { Component } from '@angular/core';
import { ComponentCardComponent } from "../../../../shared/components/common/component-card/component-card.component";
import { TableComponent } from "../../../../shared/components/table/table.component";
import { PageBreadcrumbComponent } from "../../../../shared/components/common/page-breadcrumb/page-breadcrumb.component";

@Component({
  selector: 'app-stock-move',
  standalone: true,
  imports: [ComponentCardComponent, TableComponent, PageBreadcrumbComponent],
  templateUrl: './stock-move.component.html'
})
export class StockMoveComponent {

  columns = [
    { key: 'id', label: 'Move ID', sortable: true },                       // unikalny identyfikator ruchu
    { key: 'productSku', label: 'Product SKU', sortable: true },           // identyfikator produktu
    { key: 'productName', label: 'Product Name', sortable: true },
    { key: 'fromWarehouse', label: 'From Warehouse', sortable: true },
    { key: 'fromZone', label: 'From Zone', sortable: true },
    { key: 'toWarehouse', label: 'To Warehouse', sortable: true },
    { key: 'toZone', label: 'To Zone', sortable: true },
    { key: 'quantity', label: 'Quantity', sortable: true },
    { key: 'unit', label: 'Unit', sortable: true },
    { key: 'moveType', label: 'Move Type', sortable: true },              // In / Out / Transfer
    { key: 'status', label: 'Status', sortable: true },                   // Completed / Pending / Cancelled
    { key: 'movedBy', label: 'Moved By', sortable: true },
    { key: 'movedAt', label: 'Moved At', sortable: true, type: 'date' },
    { key: 'reference', label: 'Document', sortable: true }
  ];
  
  stockMoves = [
    { id: 1, productSku: "SKU-4001", productName: "Ethernet Cable 5m", fromWarehouse: "Regional DC Kraków", fromZone: "Receiving", toWarehouse: "East DC Lublin", toZone: "Packing", quantity: 17, unit: "sets", moveType: "Transfer", status: "Completed", movedBy: "Sara Lee", movedAt: new Date("2026-02-20T03:32:08"), reference: "DOC-0001", actions: "" },
    { id: 2, productSku: "SKU-3002", productName: "Office Desk 160x80", fromWarehouse: "", fromZone: "", toWarehouse: "South Hub Wrocław", toZone: "Packing", quantity: 49, unit: "pcs", moveType: "In", status: "Completed", movedBy: "Anna Kowalska", movedAt: new Date("2026-02-17T14:51:46"), reference: "DOC-0002", actions: "" },
    { id: 3, productSku: "SKU-3002", productName: "Office Desk 160x80", fromWarehouse: "East DC Lublin", fromZone: "Receiving", toWarehouse: "South Hub Wrocław", toZone: "Packing", quantity: 18, unit: "kg", moveType: "Transfer", status: "Cancelled", movedBy: "Sara Lee", movedAt: new Date("2026-02-20T05:45:05"), reference: "DOC-0003", actions: "" },
    { id: 4, productSku: "SKU-1001", productName: "Laptop Dell XPS 13", fromWarehouse: "", fromZone: "", toWarehouse: "South Hub Wrocław", toZone: "Quality Control", quantity: 27, unit: "sets", moveType: "In", status: "Completed", movedBy: "Anna Kowalska", movedAt: new Date("2026-03-15T10:53:51"), reference: "DOC-0004", actions: "" },
    { id: 5, productSku: "SKU-3002", productName: "Office Desk 160x80", fromWarehouse: "Regional DC Kraków", fromZone: "Picking", toWarehouse: "North Hub Gdańsk", toZone: "Picking", quantity: 5, unit: "kg", moveType: "Transfer", status: "Completed", movedBy: "Tom Brown", movedAt: new Date("2026-03-07T15:07:13"), reference: "DOC-0005", actions: "" },
    { id: 6, productSku: "SKU-1003", productName: "Samsung Galaxy S24", fromWarehouse: "Central Warehouse Warsaw", fromZone: "Quality Control", toWarehouse: "South Hub Wrocław", toZone: "Receiving", quantity: 6, unit: "pcs", moveType: "Transfer", status: "Pending", movedBy: "Michael Johnson", movedAt: new Date("2026-03-17T09:00:03"), reference: "DOC-0006", actions: "" },
    { id: 7, productSku: "SKU-5002", productName: "Mechanical Keyboard", fromWarehouse: "Central Warehouse Warsaw", fromZone: "Receiving", toWarehouse: "North Hub Gdańsk", toZone: "Packing", quantity: 49, unit: "boxes", moveType: "Transfer", status: "Completed", movedBy: "Michael Johnson", movedAt: new Date("2026-02-23T06:36:02"), reference: "DOC-0007", actions: "" },
    { id: 8, productSku: "SKU-5001", productName: "Logitech Wireless Mouse", fromWarehouse: "Central Warehouse Warsaw", fromZone: "Receiving", toWarehouse: "", toZone: "", quantity: 8, unit: "boxes", moveType: "Out", status: "Pending", movedBy: "Sara Lee", movedAt: new Date("2026-03-17T06:17:16"), reference: "DOC-0008", actions: "" },
    { id: 9, productSku: "SKU-5002", productName: "Mechanical Keyboard", fromWarehouse: "East DC Lublin", fromZone: "Receiving", toWarehouse: "", toZone: "", quantity: 35, unit: "pcs", moveType: "Out", status: "Completed", movedBy: "Michael Johnson", movedAt: new Date("2026-03-03T17:42:46"), reference: "DOC-0009", actions: "" },
    { id: 10, productSku: "SKU-5001", productName: "Logitech Wireless Mouse", fromWarehouse: "", fromZone: "", toWarehouse: "North Hub Gdańsk", toZone: "Dispatch", quantity: 28, unit: "kg", moveType: "In", status: "Completed", movedBy: "John Smith", movedAt: new Date("2026-02-28T04:02:55"), reference: "DOC-0010", actions: "" },
    { id: 11, productSku: "SKU-4002", productName: "HDMI Cable 2m", fromWarehouse: "Central Warehouse Warsaw", fromZone: "Receiving", toWarehouse: "South Hub Wrocław", toZone: "Picking", quantity: 6, unit: "boxes", moveType: "Transfer", status: "Pending", movedBy: "John Smith", movedAt: new Date("2026-03-10T09:57:58"), reference: "DOC-0011", actions: "" },
    { id: 12, productSku: "SKU-2001", productName: "HP LaserJet Printer", fromWarehouse: "East DC Lublin", fromZone: "Dispatch", toWarehouse: "Regional DC Kraków", toZone: "Receiving", quantity: 27, unit: "sets", moveType: "Transfer", status: "Pending", movedBy: "Tom Brown", movedAt: new Date("2026-02-28T23:42:15"), reference: "DOC-0012", actions: "" },
    { id: 13, productSku: "SKU-5001", productName: "Logitech Wireless Mouse", fromWarehouse: "Regional DC Kraków", fromZone: "Dispatch", toWarehouse: "North Hub Gdańsk", toZone: "Receiving", quantity: 28, unit: "boxes", moveType: "Transfer", status: "Cancelled", movedBy: "John Smith", movedAt: new Date("2026-03-08T17:03:27"), reference: "DOC-0013", actions: "" },
    { id: 14, productSku: "SKU-5002", productName: "Mechanical Keyboard", fromWarehouse: "Regional DC Kraków", fromZone: "Dispatch", toWarehouse: "", toZone: "", quantity: 36, unit: "kg", moveType: "Out", status: "Pending", movedBy: "Sara Lee", movedAt: new Date("2026-02-19T10:49:50"), reference: "DOC-0014", actions: "" },
    { id: 15, productSku: "SKU-5002", productName: "Mechanical Keyboard", fromWarehouse: "South Hub Wrocław", fromZone: "Picking", toWarehouse: "Central Warehouse Warsaw", toZone: "Receiving", quantity: 5, unit: "kg", moveType: "Transfer", status: "Cancelled", movedBy: "John Smith", movedAt: new Date("2026-03-09T19:10:20"), reference: "DOC-0015", actions: "" },
    { id: 16, productSku: "SKU-1001", productName: "Laptop Dell XPS 13", fromWarehouse: "Central Warehouse Warsaw", fromZone: "Packing", toWarehouse: "North Hub Gdańsk", toZone: "Picking", quantity: 29, unit: "pcs", moveType: "Transfer", status: "Pending", movedBy: "Michael Johnson", movedAt: new Date("2026-03-14T06:48:05"), reference: "DOC-0016", actions: "" },
    { id: 17, productSku: "SKU-1003", productName: "Samsung Galaxy S24", fromWarehouse: "", fromZone: "", toWarehouse: "North Hub Gdańsk", toZone: "Packing", quantity: 37, unit: "kg", moveType: "In", status: "Completed", movedBy: "Tom Brown", movedAt: new Date("2026-03-17T23:44:35"), reference: "DOC-0017", actions: "" },
    { id: 18, productSku: "SKU-2001", productName: "HP LaserJet Printer", fromWarehouse: "Regional DC Kraków", fromZone: "Picking", toWarehouse: "", toZone: "", quantity: 16, unit: "sets", moveType: "Out", status: "Completed", movedBy: "Tom Brown", movedAt: new Date("2026-03-04T10:24:10"), reference: "DOC-0018", actions: "" },
    { id: 19, productSku: "SKU-4002", productName: "HDMI Cable 2m", fromWarehouse: "North Hub Gdańsk", fromZone: "Picking", toWarehouse: "", toZone: "", quantity: 36, unit: "kg", moveType: "Out", status: "Cancelled", movedBy: "John Smith", movedAt: new Date("2026-03-11T04:22:50"), reference: "DOC-0019", actions: "" },
    { id: 20, productSku: "SKU-1002", productName: "Apple iPhone 15", fromWarehouse: "", fromZone: "", toWarehouse: "North Hub Gdańsk", toZone: "Dispatch", quantity: 39, unit: "sets", moveType: "In", status: "Completed", movedBy: "Tom Brown", movedAt: new Date("2026-02-21T22:45:54"), reference: "DOC-0020", actions: "" },
    { id: 21, productSku: "SKU-5001", productName: "Logitech Wireless Mouse", fromWarehouse: "East DC Lublin", fromZone: "Receiving", toWarehouse: "", toZone: "", quantity: 4, unit: "kg", moveType: "Out", status: "Cancelled", movedBy: "Anna Kowalska", movedAt: new Date("2026-03-14T20:12:09"), reference: "DOC-0021", actions: "" },
    { id: 22, productSku: "SKU-5001", productName: "Logitech Wireless Mouse", fromWarehouse: "Regional DC Kraków", fromZone: "Packing", toWarehouse: "Central Warehouse Warsaw", toZone: "Dispatch", quantity: 22, unit: "boxes", moveType: "Transfer", status: "Cancelled", movedBy: "Tom Brown", movedAt: new Date("2026-02-28T13:27:35"), reference: "DOC-0022", actions: "" },
    { id: 23, productSku: "SKU-4001", productName: "Ethernet Cable 5m", fromWarehouse: "", fromZone: "", toWarehouse: "South Hub Wrocław", toZone: "Picking", quantity: 22, unit: "kg", moveType: "In", status: "Pending", movedBy: "Michael Johnson", movedAt: new Date("2026-02-22T21:37:10"), reference: "DOC-0023", actions: "" },
    { id: 24, productSku: "SKU-5002", productName: "Mechanical Keyboard", fromWarehouse: "North Hub Gdańsk", fromZone: "Dispatch", toWarehouse: "East DC Lublin", toZone: "Quality Control", quantity: 26, unit: "sets", moveType: "Transfer", status: "Pending", movedBy: "Sara Lee", movedAt: new Date("2026-03-06T22:34:33"), reference: "DOC-0024", actions: "" },
    { id: 25, productSku: "SKU-3001", productName: "Office Chair Ergonomic", fromWarehouse: "Central Warehouse Warsaw", fromZone: "Packing", toWarehouse: "South Hub Wrocław", toZone: "Quality Control", quantity: 45, unit: "kg", moveType: "Transfer", status: "Pending", movedBy: "Tom Brown", movedAt: new Date("2026-03-07T15:12:27"), reference: "DOC-0025", actions: "" },
    { id: 26, productSku: "SKU-4002", productName: "HDMI Cable 2m", fromWarehouse: "Central Warehouse Warsaw", fromZone: "Picking", toWarehouse: "", toZone: "", quantity: 24, unit: "kg", moveType: "Out", status: "Pending", movedBy: "John Smith", movedAt: new Date("2026-03-08T16:47:33"), reference: "DOC-0026", actions: "" },
    { id: 27, productSku: "SKU-3001", productName: "Office Chair Ergonomic", fromWarehouse: "", fromZone: "", toWarehouse: "North Hub Gdańsk", toZone: "Receiving", quantity: 29, unit: "pcs", moveType: "In", status: "Pending", movedBy: "Michael Johnson", movedAt: new Date("2026-02-18T15:41:16"), reference: "DOC-0027", actions: "" },
    { id: 28, productSku: "SKU-5001", productName: "Logitech Wireless Mouse", fromWarehouse: "", fromZone: "", toWarehouse: "East DC Lublin", toZone: "Receiving", quantity: 44, unit: "kg", moveType: "In", status: "Pending", movedBy: "Anna Kowalska", movedAt: new Date("2026-02-28T16:08:22"), reference: "DOC-0028", actions: "" },
    { id: 29, productSku: "SKU-1002", productName: "Apple iPhone 15", fromWarehouse: "South Hub Wrocław", fromZone: "Picking", toWarehouse: "East DC Lublin", toZone: "Receiving", quantity: 28, unit: "pcs", moveType: "Transfer", status: "Cancelled", movedBy: "Sara Lee", movedAt: new Date("2026-03-07T20:11:56"), reference: "DOC-0029", actions: "" },
    { id: 30, productSku: "SKU-1003", productName: "Samsung Galaxy S24", fromWarehouse: "", fromZone: "", toWarehouse: "Regional DC Kraków", toZone: "Picking", quantity: 8, unit: "pcs", moveType: "In", status: "Pending", movedBy: "Sara Lee", movedAt: new Date("2026-03-06T14:21:55"), reference: "DOC-0030", actions: "" },
    { id: 31, productSku: "SKU-4002", productName: "HDMI Cable 2m", fromWarehouse: "East DC Lublin", fromZone: "Picking", toWarehouse: "", toZone: "", quantity: 32, unit: "pcs", moveType: "Out", status: "Completed", movedBy: "John Smith", movedAt: new Date("2026-03-11T21:10:29"), reference: "DOC-0031", actions: "" },
    { id: 32, productSku: "SKU-2001", productName: "HP LaserJet Printer", fromWarehouse: "South Hub Wrocław", fromZone: "Packing", toWarehouse: "", toZone: "", quantity: 37, unit: "sets", moveType: "Out", status: "Cancelled", movedBy: "Sara Lee", movedAt: new Date("2026-02-17T17:48:24"), reference: "DOC-0032", actions: "" },
    { id: 33, productSku: "SKU-1001", productName: "Laptop Dell XPS 13", fromWarehouse: "Central Warehouse Warsaw", fromZone: "Packing", toWarehouse: "South Hub Wrocław", toZone: "Quality Control", quantity: 25, unit: "boxes", moveType: "Transfer", status: "Pending", movedBy: "Anna Kowalska", movedAt: new Date("2026-03-11T15:21:16"), reference: "DOC-0033", actions: "" },
    { id: 34, productSku: "SKU-4001", productName: "Ethernet Cable 5m", fromWarehouse: "", fromZone: "", toWarehouse: "Regional DC Kraków", toZone: "Picking", quantity: 9, unit: "boxes", moveType: "In", status: "Pending", movedBy: "Michael Johnson", movedAt: new Date("2026-03-16T20:42:21"), reference: "DOC-0034", actions: "" },
    { id: 35, productSku: "SKU-1001", productName: "Laptop Dell XPS 13", fromWarehouse: "", fromZone: "", toWarehouse: "North Hub Gdańsk", toZone: "Picking", quantity: 2, unit: "pcs", moveType: "In", status: "Completed", movedBy: "Michael Johnson", movedAt: new Date("2026-02-20T06:59:06"), reference: "DOC-0035", actions: "" },
    { id: 36, productSku: "SKU-3001", productName: "Office Chair Ergonomic", fromWarehouse: "", fromZone: "", toWarehouse: "East DC Lublin", toZone: "Quality Control", quantity: 31, unit: "sets", moveType: "In", status: "Pending", movedBy: "Anna Kowalska", movedAt: new Date("2026-03-01T01:12:40"), reference: "DOC-0036", actions: "" },
    { id: 37, productSku: "SKU-1003", productName: "Samsung Galaxy S24", fromWarehouse: "", fromZone: "", toWarehouse: "East DC Lublin", toZone: "Picking", quantity: 34, unit: "boxes", moveType: "In", status: "Completed", movedBy: "Michael Johnson", movedAt: new Date("2026-03-03T01:51:11"), reference: "DOC-0037", actions: "" },
    { id: 38, productSku: "SKU-4002", productName: "HDMI Cable 2m", fromWarehouse: "", fromZone: "", toWarehouse: "Regional DC Kraków", toZone: "Picking", quantity: 19, unit: "pcs", moveType: "In", status: "Completed", movedBy: "Michael Johnson", movedAt: new Date("2026-03-04T07:03:04"), reference: "DOC-0038", actions: "" },
    { id: 39, productSku: "SKU-3001", productName: "Office Chair Ergonomic", fromWarehouse: "Regional DC Kraków", fromZone: "Dispatch", toWarehouse: "", toZone: "", quantity: 31, unit: "boxes", moveType: "Out", status: "Completed", movedBy: "Michael Johnson", movedAt: new Date("2026-03-10T09:09:53"), reference: "DOC-0039", actions: "" },
    { id: 40, productSku: "SKU-1001", productName: "Laptop Dell XPS 13", fromWarehouse: "Regional DC Kraków", fromZone: "Picking", toWarehouse: "East DC Lublin", toZone: "Dispatch", quantity: 8, unit: "sets", moveType: "Transfer", status: "Cancelled", movedBy: "John Smith", movedAt: new Date("2026-03-04T04:43:55"), reference: "DOC-0040", actions: "" },
    { id: 41, productSku: "SKU-3001", productName: "Office Chair Ergonomic", fromWarehouse: "South Hub Wrocław", fromZone: "Dispatch", toWarehouse: "", toZone: "", quantity: 7, unit: "sets", moveType: "Out", status: "Pending", movedBy: "Tom Brown", movedAt: new Date("2026-02-27T15:37:37"), reference: "DOC-0041", actions: "" },
    { id: 42, productSku: "SKU-5001", productName: "Logitech Wireless Mouse", fromWarehouse: "", fromZone: "", toWarehouse: "South Hub Wrocław", toZone: "Dispatch", quantity: 40, unit: "pcs", moveType: "In", status: "Pending", movedBy: "Sara Lee", movedAt: new Date("2026-03-03T23:29:17"), reference: "DOC-0042", actions: "" },
    { id: 43, productSku: "SKU-5002", productName: "Mechanical Keyboard", fromWarehouse: "South Hub Wrocław", fromZone: "Packing", toWarehouse: "Central Warehouse Warsaw", toZone: "Receiving", quantity: 21, unit: "pcs", moveType: "Transfer", status: "Pending", movedBy: "Sara Lee", movedAt: new Date("2026-03-07T02:55:26"), reference: "DOC-0043", actions: "" },
    { id: 44, productSku: "SKU-4001", productName: "Ethernet Cable 5m", fromWarehouse: "", fromZone: "", toWarehouse: "Central Warehouse Warsaw", toZone: "Packing", quantity: 7, unit: "pcs", moveType: "In", status: "Pending", movedBy: "Anna Kowalska", movedAt: new Date("2026-03-08T06:19:48"), reference: "DOC-0044", actions: "" },
    { id: 45, productSku: "SKU-3002", productName: "Office Desk 160x80", fromWarehouse: "East DC Lublin", fromZone: "Dispatch", toWarehouse: "", toZone: "", quantity: 4, unit: "boxes", moveType: "Out", status: "Pending", movedBy: "Tom Brown", movedAt: new Date("2026-03-11T23:15:07"), reference: "DOC-0045", actions: "" },
    { id: 46, productSku: "SKU-4002", productName: "HDMI Cable 2m", fromWarehouse: "", fromZone: "", toWarehouse: "South Hub Wrocław", toZone: "Packing", quantity: 46, unit: "kg", moveType: "In", status: "Pending", movedBy: "Michael Johnson", movedAt: new Date("2026-03-05T11:31:32"), reference: "DOC-0046", actions: "" },
    { id: 47, productSku: "SKU-3002", productName: "Office Desk 160x80", fromWarehouse: "Central Warehouse Warsaw", fromZone: "Packing", toWarehouse: "", toZone: "", quantity: 14, unit: "pcs", moveType: "Out", status: "Pending", movedBy: "Anna Kowalska", movedAt: new Date("2026-03-15T23:27:13"), reference: "DOC-0047", actions: "" },
    { id: 48, productSku: "SKU-1002", productName: "Apple iPhone 15", fromWarehouse: "South Hub Wrocław", fromZone: "Quality Control", toWarehouse: "East DC Lublin", toZone: "Picking", quantity: 34, unit: "pcs", moveType: "Transfer", status: "Pending", movedBy: "John Smith", movedAt: new Date("2026-03-17T16:46:38"), reference: "DOC-0048", actions: "" }
  ];
}
