export interface DocumentItem {
    id: string,
    quantity: number,
    documentId: string,
    documentNumber?: string,
    productId: string,
    productName?: string,
    productBatchId?: string,
    productBatchNumber?: string,
    sourceZoneId: string,
    sourceZoneCode?: string,
    sourceZoneName?: string,
    targetZoneId: string,
    targetZoneCode?: string,
    targetZoneName?: string,
}
